// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sansumuehxdnmvnswygr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbnN1bXVlaHhkbm12bnN3eWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyOTgxMjgsImV4cCI6MjA4Njg3NDEyOH0.lbUcdUfXp504sAY4jT3-4GnuDMThi2RQDfwGDDdg-JU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});